variable "cidr" {}
variable "env" {}
variable "subnets" {}
variable "availability_zones" {}
variable "name" {}
variable "peering_vpcs" {}
variable "def_vpc_cidr" {}
variable "zone_id" {}
variable "def_vpc_id" {}