# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: minimal-ingress
#   namespace: kube-system
#   annotations: 
#      external-dns.alpha.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: "testingextdns.cloudapps.today"
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/bar"
#         backend:
#           service:
#             name: ingress-nginx-controller
#             port:
#               number: 80